databases:
  - name: playto-db
    databaseName: playto_db
    plan: free

services:
  - type: redis
    name: playto-redis
    plan: free
    ipAllowList: []

  - type: web
    name: playto-web
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn playto_payout.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: playto-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: playto-redis
          type: redis
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: playto_payout.settings
      - key: PYTHON_VERSION
        value: 3.11.0

  - type: worker
    name: playto-celery-worker
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A playto_payout worker -l info
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: playto-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: playto-redis
          type: redis
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: playto_payout.settings

  - type: worker
    name: playto-celery-beat
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A playto_payout beat -l info
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: playto-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: playto-redis
          type: redis
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: playto_payout.settings
